#!/usr/bin/env python3
"""Generate feat_norm.{c,h} from norm_mean.npy + norm_std.npy.

The TFLM int8 model in models/flat26_baseline_int8.tflite was calibrated
against MFCC features that have been per-coefficient/channel-normalized:

    normalized[t][k][c] = (mfcc[t][k][c] - mean[k][c]) / std[k][c]

The mean and std are broadcast over frames — they live as float32 NumPy
arrays of shape (1, 1, 20, 3) (= 60 floats each). This script reads the
.npy files, flattens them in NHWC C-order to match the firmware's
`out[t * 60 + k * 3 + c]` indexing, and emits a C file with two static
const float[60] arrays plus an extern declaration header.

The generated files are checked into the firmware tree at:

    components/letter_recognizer/feat_norm.c
    components/letter_recognizer/include/feat_norm.h

so the IDF build does not depend on Python at compile time. Re-run this
script whenever the model handoff (models/norm_*.npy) changes.

Run from the project root:

    python3 tools/gen_norm_arrays/gen_norm_arrays.py

Or via Make:

    make -C tools/gen_norm_arrays gen
"""
import argparse
import os
import sys
import textwrap

import numpy as np

DEFAULT_MEAN_NPY = "models/norm_mean.npy"
DEFAULT_STD_NPY = "models/norm_std.npy"
DEFAULT_C_OUT = "components/letter_recognizer/feat_norm.c"
DEFAULT_H_OUT = "components/letter_recognizer/include/feat_norm.h"

EXPECTED_LEN = 60  # 20 MFCC × 3 channels — matches SPELL_MFCC_N_COEFFS × SPELL_FEAT_N_CHANNELS


def load_norm_array(path: str, label: str) -> np.ndarray:
    arr = np.load(path)
    if arr.dtype != np.float32:
        sys.exit(f"{path}: expected float32, got {arr.dtype}")
    flat = arr.reshape(-1).astype(np.float32, copy=False)
    if flat.size != EXPECTED_LEN:
        sys.exit(
            f"{path}: expected {EXPECTED_LEN} elements (20 MFCC × 3 ch), "
            f"got {flat.size} (shape={arr.shape})"
        )
    if label == "std":
        if not np.all(flat > 0.0):
            sys.exit(f"{path}: std must be strictly positive, found <=0")
    return flat


def format_floats(values: np.ndarray, indent: str = "    ") -> str:
    lines = []
    # 20 rows × 3 cols matches the (k, c) layout one-per-line for readability.
    cols = 3
    for k in range(20):
        chunk = values[k * cols : (k + 1) * cols]
        formatted = ", ".join(f"{v:.9e}f" for v in chunk)
        # Trailing comma for the last row keeps later additions diff-clean.
        lines.append(f"{indent}{formatted},")
    return "\n".join(lines)


C_HEADER_BANNER = textwrap.dedent(
    """\
    /**
     * @file feat_norm.{ext}
     * @brief Per-coefficient/channel normalization arrays for flat26_baseline_int8.
     *
     * AUTOGENERATED by tools/gen_norm_arrays/gen_norm_arrays.py from
     * models/norm_mean.npy and models/norm_std.npy. Do NOT edit by hand —
     * re-run the script whenever the model handoff changes.
     *
     * Layout matches feat_extract_compute()'s output (NHWC, row-major):
     *
     *   out[t * 60 + k * 3 + c]    where 60 = SPELL_MFCC_N_COEFFS *
     *                              SPELL_FEAT_N_CHANNELS
     *
     * Per-element broadcast over frames is therefore
     *
     *   normalized[i] = (out[i] - mean[i % 60]) / std[i % 60]
     *
     * The (k, c) pair for offset (i % 60) is (k = (i % 60) / 3,
     * c = (i % 60) % 3).
     */
    """
)


def emit_c(values_mean: np.ndarray, values_std: np.ndarray, path: str) -> None:
    body = textwrap.dedent(
        """\
        #include "feat_norm.h"

        const float spell_feat_norm_mean[SPELL_FEAT_NORM_LEN] = {{
        {mean_values}
        }};

        const float spell_feat_norm_std[SPELL_FEAT_NORM_LEN] = {{
        {std_values}
        }};
        """
    )
    with open(path, "w") as f:
        f.write(C_HEADER_BANNER.format(ext="c"))
        f.write("\n")
        f.write(
            body.format(
                mean_values=format_floats(values_mean),
                std_values=format_floats(values_std),
            )
        )


H_BODY = textwrap.dedent(
    """\
    #pragma once

    #include "spell_config.h"

    #ifdef __cplusplus
    extern "C" {
    #endif

    // 20 MFCC coefficients × 3 channels (static + Δ + ΔΔ) = 60.
    // Mirrored against SPELL_MFCC_N_COEFFS × SPELL_FEAT_N_CHANNELS so a
    // future channel/coef change in spell_config.h trips a static_assert
    // build-time check rather than silently misindexing the runtime.
    #define SPELL_FEAT_NORM_LEN \\
        (SPELL_MFCC_N_COEFFS * SPELL_FEAT_N_CHANNELS)

    _Static_assert(SPELL_FEAT_NORM_LEN == 60,
                   "feat_norm arrays were generated for 20 MFCC × 3 channels; "
                   "regenerate via tools/gen_norm_arrays after changing either constant.");

    extern const float spell_feat_norm_mean[SPELL_FEAT_NORM_LEN];
    extern const float spell_feat_norm_std [SPELL_FEAT_NORM_LEN];

    #ifdef __cplusplus
    }  // extern "C"
    #endif
    """
)


def emit_h(path: str) -> None:
    with open(path, "w") as f:
        f.write(C_HEADER_BANNER.format(ext="h"))
        f.write("\n")
        f.write(H_BODY)


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--mean-npy", default=DEFAULT_MEAN_NPY)
    p.add_argument("--std-npy", default=DEFAULT_STD_NPY)
    p.add_argument("--c-out", default=DEFAULT_C_OUT)
    p.add_argument("--h-out", default=DEFAULT_H_OUT)
    p.add_argument(
        "--check",
        action="store_true",
        help="Round-trip self-check: parse the emitted .c and verify the values match the .npy inputs (≤1e-7 tolerance). Exits non-zero on mismatch.",
    )
    return p.parse_args()


def parse_c_array(c_path: str, name: str) -> np.ndarray:
    """Round-trip self-check helper. Pulls the float literals out of the
    generated .c file by name. Tolerant of whitespace, commas, and 'f' suffix."""
    import re

    with open(c_path) as f:
        text = f.read()
    pattern = rf"const\s+float\s+{re.escape(name)}\s*\[[^\]]+\]\s*=\s*\{{(.*?)\}}"
    match = re.search(pattern, text, re.DOTALL)
    if not match:
        sys.exit(f"{c_path}: could not find array '{name}' for round-trip check")
    body = match.group(1)
    floats = re.findall(r"[-+]?\d+\.\d+e[-+]?\d+f?", body)
    if len(floats) != EXPECTED_LEN:
        sys.exit(
            f"{c_path}: array '{name}' has {len(floats)} floats, expected {EXPECTED_LEN}"
        )
    parsed = np.asarray(
        [float(f.rstrip("f")) for f in floats], dtype=np.float32
    )
    return parsed


def main() -> int:
    args = parse_args()

    if not os.path.exists(args.mean_npy):
        sys.exit(f"{args.mean_npy}: not found (run from project root)")
    if not os.path.exists(args.std_npy):
        sys.exit(f"{args.std_npy}: not found (run from project root)")

    mean = load_norm_array(args.mean_npy, "mean")
    std = load_norm_array(args.std_npy, "std")

    os.makedirs(os.path.dirname(args.h_out), exist_ok=True)
    os.makedirs(os.path.dirname(args.c_out), exist_ok=True)

    emit_h(args.h_out)
    emit_c(mean, std, args.c_out)

    print(
        f"wrote {args.h_out} ({EXPECTED_LEN} extern decls)\n"
        f"wrote {args.c_out} (mean range {mean.min():+.4f}..{mean.max():+.4f}, "
        f"std range {std.min():.4f}..{std.max():.4f})"
    )

    if args.check:
        parsed_mean = parse_c_array(args.c_out, "spell_feat_norm_mean")
        parsed_std = parse_c_array(args.c_out, "spell_feat_norm_std")
        # 9-significant-digit format introduces ≤1 ULP rounding; tolerance 1e-7 is generous.
        np.testing.assert_allclose(parsed_mean, mean, atol=1e-7, rtol=0)
        np.testing.assert_allclose(parsed_std, std, atol=1e-7, rtol=0)
        print(f"round-trip check: OK ({EXPECTED_LEN} mean + {EXPECTED_LEN} std floats match)")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
