idf_component_register(
    SRCS
        "feat_extract.c"
        "letter_recognizer.cpp"
        "w_detector_core.c"
    INCLUDE_DIRS
        "include"
    REQUIRES
        spell_common
        audio_capture
        esp-dsp
        esp-tflite-micro
        esp_event
        esp_timer
        esp_partition
)
