/**
 * @file feat_norm.h
 * @brief Per-coefficient/channel normalization arrays for flat26_baseline_int8.
 *
 * AUTOGENERATED by tools/gen_norm_arrays/gen_norm_arrays.py from
 * models/norm_mean.npy and models/norm_std.npy. Do NOT edit by hand —
 * re-run the script whenever the model handoff changes.
 *
 * Layout matches feat_extract_compute()'s output (NHWC, row-major):
 *
 *   out[t * 60 + k * 3 + c]    where 60 = SPELL_MFCC_N_COEFFS *
 *                              SPELL_FEAT_N_CHANNELS
 *
 * Per-element broadcast over frames is therefore
 *
 *   normalized[i] = (out[i] - mean[i % 60]) / std[i % 60]
 *
 * The (k, c) pair for offset (i % 60) is (k = (i % 60) / 3,
 * c = (i % 60) % 3).
 */

#pragma once

#include "spell_config.h"

#ifdef __cplusplus
extern "C" {
#endif

// 20 MFCC coefficients × 3 channels (static + Δ + ΔΔ) = 60.
// Mirrored against SPELL_MFCC_N_COEFFS × SPELL_FEAT_N_CHANNELS so a
// future channel/coef change in spell_config.h trips a static_assert
// build-time check rather than silently misindexing the runtime.
#define SPELL_FEAT_NORM_LEN \
    (SPELL_MFCC_N_COEFFS * SPELL_FEAT_N_CHANNELS)

_Static_assert(SPELL_FEAT_NORM_LEN == 60,
               "feat_norm arrays were generated for 20 MFCC × 3 channels; "
               "regenerate via tools/gen_norm_arrays after changing either constant.");

extern const float spell_feat_norm_mean[SPELL_FEAT_NORM_LEN];
extern const float spell_feat_norm_std [SPELL_FEAT_NORM_LEN];

#ifdef __cplusplus
}  // extern "C"
#endif
